package bead

import (
	"strings"
	"testing"
)

// This file ports the structure of v2's Bead hashing/CAS tests
// (git show v2.2.0:core/store/cas_test.go on the v2-maintenance branch,
// specifically TestSaveAndLoadFromCAS / TestSaveToCAS_HashIsDeterministic)
// to v3's bead package: fixed-input round trip, hash determinism, and (new
// in v3) explicit tamper detection via Verify.
//
// v3's hash-target field set differs from v2 (see specs/DESIGN_v3.md §4):
// v2 hashed {type, timestamp, parents, content} via a plain
// json.MarshalIndent (no canonicalization scheme, no author/antigens/
// evidence, no dedup/sort of parents). v3.0 hashed
// {type, timestamp, author, parents, antigens, content, evidence} via RFC
// 8785 (JCS), with parents/antigens normalized (dedup + sort) first.
//
// v3.1 (specs/DESIGN_v3.1_draft.md §2, "事実と解釈の二層分離") changed the
// hash-target field set again: antigens is removed entirely (tag derivation
// moved to the index projection, see antigen.Extract) and amends/retracts
// are added (dedup+sort normalized exactly like parents). The payload shape
// is now {type, timestamp, author, parents, amends, retracts, content,
// evidence}. Because the payload shape itself changed a second time, every
// golden ID below was regenerated by running this package's own
// implementation once against the v3.1 field set (see
// TestGoldenID_FixedBead / TestGoldenID_Minimal) and is pinned as a new
// regression baseline: v3.0's golden values do not carry over (removing
// antigens and adding amends/retracts changes the JCS payload's key set, so
// every existing v3.0 Bead ID is intentionally NOT reproducible under this
// version — the one-time, all-at-once re-ingest called for by
// specs/DESIGN_v3.1_draft.md §0 point 7 is what absorbs this). If a future
// change to Canonicalize/ComputeID (or an upstream gowebpki/jcs version
// bump) alters these values again, that is a signal requiring explicit
// review — Bead IDs must never change silently, since they are the join key
// for a Merkle DAG.

// fixedBead is the canonical fixture used by the golden hash tests below.
func fixedBead() Bead {
	return Bead{
		Type:      "observation",
		Timestamp: "2026-03-01T10:00:00Z",
		Author:    "did:medbeads:doctor:12345",
		Parents:   []string{"b2", "a1"},
		Amends:    []string{"m2", "m1"},
		Retracts:  []string{"r2", "r1"},
		Content: map[string]any{
			"bp":   "120/80",
			"note": "stable",
		},
		Evidence: []Evidence{
			{URI: "s3://bucket/ct.dcm", MimeType: "application/dicom", Hash: "sha256:abc123"},
		},
	}
}

// TestGoldenID_FixedBead pins ComputeID's output for a fixed, representative
// Bead (all hash-target fields populated, including amends/retracts). This
// value was generated by running ComputeID once against the v3.1
// implementation in this package (see this file's header comment on why
// v3.0's golden values do not carry over) and is now a regression baseline:
// any future diff must explain why this constant changed.
func TestGoldenID_FixedBead(t *testing.T) {
	const wantID = "50d8b41778d2080b22a6c0b9951c6aef74f5182a605d9423ab5f43878ebec829"
	const wantCanonical = `{"amends":["m1","m2"],"author":"did:medbeads:doctor:12345",` +
		`"content":{"bp":"120/80","note":"stable"},` +
		`"evidence":[{"hash":"sha256:abc123","mime_type":"application/dicom","uri":"s3://bucket/ct.dcm"}],` +
		`"parents":["a1","b2"],"retracts":["r1","r2"],"timestamp":"2026-03-01T10:00:00Z","type":"observation"}`

	b := fixedBead()

	canon, err := Canonicalize(b)
	if err != nil {
		t.Fatalf("Canonicalize: %v", err)
	}
	if string(canon) != wantCanonical {
		t.Errorf("Canonicalize mismatch:\n got  = %s\n want = %s", canon, wantCanonical)
	}

	id, err := ComputeID(b)
	if err != nil {
		t.Fatalf("ComputeID: %v", err)
	}
	if id != wantID {
		t.Errorf("ComputeID = %s, want %s", id, wantID)
	}
	if len(id) != HexIDLen {
		t.Errorf("ComputeID length = %d, want %d", len(id), HexIDLen)
	}
}

// TestGoldenID_Minimal pins ComputeID for a Bead with only the required
// fields set (no author, no evidence, empty parents/amends/retracts) — the
// case a patient_registration root Bead will typically hit. Confirms empty
// parents/amends/retracts canonicalize as JSON `[]`, not `null` or an
// omitted key.
func TestGoldenID_Minimal(t *testing.T) {
	const wantID = "36d7b60d4c870e46aedd1c069ac4c747b956b3aa36b6d8a1abe520ab55959acd"
	const wantCanonical = `{"amends":[],"content":{"name":"Test Patient"},"parents":[],` +
		`"retracts":[],"timestamp":"2026-01-01T00:00:00Z","type":"patient_registration"}`

	b := Bead{
		Type:      "patient_registration",
		Timestamp: "2026-01-01T00:00:00Z",
		Content:   map[string]any{"name": "Test Patient"},
	}

	canon, err := Canonicalize(b)
	if err != nil {
		t.Fatalf("Canonicalize: %v", err)
	}
	if string(canon) != wantCanonical {
		t.Errorf("Canonicalize mismatch:\n got  = %s\n want = %s", canon, wantCanonical)
	}

	id, err := ComputeID(b)
	if err != nil {
		t.Fatalf("ComputeID: %v", err)
	}
	if id != wantID {
		t.Errorf("ComputeID = %s, want %s", id, wantID)
	}
}

// TestComputeID_Deterministic ports v2's TestSaveToCAS_HashIsDeterministic:
// hashing the identical Bead value twice must yield the identical ID.
func TestComputeID_Deterministic(t *testing.T) {
	b := fixedBead()

	id1, err := ComputeID(b)
	if err != nil {
		t.Fatalf("first ComputeID: %v", err)
	}
	id2, err := ComputeID(b)
	if err != nil {
		t.Fatalf("second ComputeID: %v", err)
	}
	if id1 != id2 {
		t.Errorf("identical Beads produced different IDs: %q vs %q", id1, id2)
	}
}

// TestComputeID_OrderIndependent verifies specs/DESIGN_v3.1_draft.md §2:
// parents, amends, and retracts are deduplicated and sorted before hashing,
// so their input order (and any duplicate entries) does not affect the ID.
// This is what makes "same content, same ID" hold regardless of how a
// client happened to list a Bead's parents/amends/retracts.
func TestComputeID_OrderIndependent(t *testing.T) {
	base := fixedBead()
	baseID, err := ComputeID(base)
	if err != nil {
		t.Fatalf("ComputeID(base): %v", err)
	}

	variants := []struct {
		name string
		b    Bead
	}{
		{
			name: "parents reversed",
			b: func() Bead {
				v := base
				v.Parents = []string{"a1", "b2"} // base has {"b2", "a1"}
				return v
			}(),
		},
		{
			name: "amends reversed",
			b: func() Bead {
				v := base
				v.Amends = []string{"m1", "m2"} // base has {"m2", "m1"}
				return v
			}(),
		},
		{
			name: "retracts reversed",
			b: func() Bead {
				v := base
				v.Retracts = []string{"r1", "r2"} // base has {"r2", "r1"}
				return v
			}(),
		},
		{
			name: "parents, amends, retracts with duplicates",
			b: func() Bead {
				v := base
				v.Parents = []string{"a1", "b2", "a1", "b2", "b2"}
				v.Amends = []string{"m1", "m2", "m1", "m1"}
				v.Retracts = []string{"r1", "r2", "r2", "r2"}
				return v
			}(),
		},
	}

	for _, tc := range variants {
		t.Run(tc.name, func(t *testing.T) {
			id, err := ComputeID(tc.b)
			if err != nil {
				t.Fatalf("ComputeID: %v", err)
			}
			if id != baseID {
				t.Errorf("ComputeID(%s) = %s, want %s (same as base)", tc.name, id, baseID)
			}
		})
	}
}

// TestComputeID_ExcludesClearanceAndSignature verifies specs/DESIGN_v3.md §4:
// clearance and signature are outside the hash. Changing either must leave
// the ID unchanged, since clearance is a mutable access-control overlay and
// signature signs the ID itself (a self-referential field cannot be part of
// its own hash input).
func TestComputeID_ExcludesClearanceAndSignature(t *testing.T) {
	base := fixedBead()
	baseID, err := ComputeID(base)
	if err != nil {
		t.Fatalf("ComputeID(base): %v", err)
	}

	withClearance := base
	withClearance.Clearance = &Clearance{
		DeniedRoles: []string{"insurance", "researcher"},
		Reason:      "psychiatric record",
	}
	withClearance.Signature = "base64:deadbeef=="

	id, err := ComputeID(withClearance)
	if err != nil {
		t.Fatalf("ComputeID(withClearance): %v", err)
	}
	if id != baseID {
		t.Errorf("adding Clearance/Signature changed the ID: got %s, want %s (unchanged)", id, baseID)
	}
}

// TestVerify_DetectsContentTamper ports the spirit of v2's CAS round-trip
// test but adds the explicit tamper-detection check v2 never had: mutating
// Content by a single character after ID assignment must make Verify fail.
func TestVerify_DetectsContentTamper(t *testing.T) {
	b, err := WithID(fixedBead())
	if err != nil {
		t.Fatalf("WithID: %v", err)
	}
	if err := Verify(b); err != nil {
		t.Fatalf("Verify(untampered) = %v, want nil", err)
	}

	tampered := b
	tampered.Content = map[string]any{
		"bp":   "120/81", // one character changed: 0 -> 1
		"note": "stable",
	}
	if err := Verify(tampered); err == nil {
		t.Error("Verify(tampered content) = nil, want error")
	}
}

// TestVerify_DetectsFieldTamper extends tamper detection to every
// hash-target field, confirming each one is actually load-bearing in the
// hash (a common bug is to forget to include a newly added field).
func TestVerify_DetectsFieldTamper(t *testing.T) {
	base, err := WithID(fixedBead())
	if err != nil {
		t.Fatalf("WithID: %v", err)
	}

	mutations := []struct {
		name   string
		mutate func(Bead) Bead
	}{
		{"type", func(b Bead) Bead { b.Type = "condition"; return b }},
		{"timestamp", func(b Bead) Bead { b.Timestamp = "2026-03-01T10:00:01Z"; return b }},
		{"author", func(b Bead) Bead { b.Author = "did:medbeads:doctor:99999"; return b }},
		{"parents", func(b Bead) Bead { b.Parents = []string{"c3"}; return b }},
		{"amends", func(b Bead) Bead { b.Amends = []string{"m3"}; return b }},
		{"retracts", func(b Bead) Bead { b.Retracts = []string{"r3"}; return b }},
		{"evidence", func(b Bead) Bead {
			b.Evidence = []Evidence{{URI: "s3://bucket/other.dcm", MimeType: "application/dicom", Hash: "sha256:xyz"}}
			return b
		}},
	}

	for _, m := range mutations {
		t.Run(m.name, func(t *testing.T) {
			tampered := m.mutate(base)
			if err := Verify(tampered); err == nil {
				t.Errorf("Verify after mutating %s = nil, want error", m.name)
			}
		})
	}
}

// TestVerify_EmptyID confirms Verify rejects a Bead that was never assigned
// an ID, rather than silently treating "" as valid.
func TestVerify_EmptyID(t *testing.T) {
	b := fixedBead() // ID left empty
	if err := Verify(b); err == nil {
		t.Error("Verify(no ID) = nil, want error")
	}
}

// TestVerify_ClearanceSignatureDoNotAffectVerify confirms Verify still
// passes after Clearance/Signature are changed post-hoc, matching
// TestComputeID_ExcludesClearanceAndSignature but through the Verify path a
// caller would actually use.
func TestVerify_ClearanceSignatureDoNotAffectVerify(t *testing.T) {
	b, err := WithID(fixedBead())
	if err != nil {
		t.Fatalf("WithID: %v", err)
	}

	b.Clearance = &Clearance{DeniedRoles: []string{"insurance"}}
	b.Signature = "base64:deadbeef=="

	if err := Verify(b); err != nil {
		t.Errorf("Verify after setting Clearance/Signature = %v, want nil", err)
	}
}

// TestNormalize_DedupAndSort exercises Normalize (and, through it,
// normalizeStrings) directly, across Parents/Amends/Retracts.
func TestNormalize_DedupAndSort(t *testing.T) {
	b := Bead{
		Type:      "encounter",
		Timestamp: "2026-01-01T00:00:00Z",
		Parents:   []string{"z9", "a1", "z9", "m5", "a1"},
		Amends:    []string{"m9", "m1", "m9"},
		Retracts:  []string{"r9", "r1", "r9"},
		Content:   map[string]any{},
	}

	n := Normalize(b)

	wantParents := []string{"a1", "m5", "z9"}
	if !equalStrings(n.Parents, wantParents) {
		t.Errorf("Normalize(b).Parents = %v, want %v", n.Parents, wantParents)
	}

	wantAmends := []string{"m1", "m9"}
	if !equalStrings(n.Amends, wantAmends) {
		t.Errorf("Normalize(b).Amends = %v, want %v", n.Amends, wantAmends)
	}

	wantRetracts := []string{"r1", "r9"}
	if !equalStrings(n.Retracts, wantRetracts) {
		t.Errorf("Normalize(b).Retracts = %v, want %v", n.Retracts, wantRetracts)
	}
}

// TestNormalize_NilBecomesEmptySlice confirms nil Parents/Amends/Retracts
// normalize to a non-nil empty slice (so they marshal as JSON `[]`, keeping
// the hash payload shape stable and matching TestGoldenID_Minimal's
// canonical form).
func TestNormalize_NilBecomesEmptySlice(t *testing.T) {
	b := Bead{Type: "t", Timestamp: "2026-01-01T00:00:00Z", Content: map[string]any{}}
	n := Normalize(b)
	if n.Parents == nil {
		t.Error("Normalize(b).Parents is nil, want non-nil empty slice")
	}
	if len(n.Parents) != 0 {
		t.Errorf("Normalize(b).Parents = %v, want empty", n.Parents)
	}
	if n.Amends == nil {
		t.Error("Normalize(b).Amends is nil, want non-nil empty slice")
	}
	if len(n.Amends) != 0 {
		t.Errorf("Normalize(b).Amends = %v, want empty", n.Amends)
	}
	if n.Retracts == nil {
		t.Error("Normalize(b).Retracts is nil, want non-nil empty slice")
	}
	if len(n.Retracts) != 0 {
		t.Errorf("Normalize(b).Retracts = %v, want empty", n.Retracts)
	}
}

// TestFormatIDAndParseID exercises the "sha256:" display-prefix helpers.
// Per specs/DESIGN_v3.md §4, the prefix is a presentation-layer concern only
// — internal IDs (as returned by ComputeID) are always plain hex.
func TestFormatIDAndParseID(t *testing.T) {
	b, err := WithID(fixedBead())
	if err != nil {
		t.Fatalf("WithID: %v", err)
	}

	if strings.HasPrefix(b.ID, IDPrefix) {
		t.Errorf("ComputeID output has unexpected %q prefix: %s", IDPrefix, b.ID)
	}

	formatted := FormatID(b.ID)
	if formatted != IDPrefix+b.ID {
		t.Errorf("FormatID(%s) = %s, want %s%s", b.ID, formatted, IDPrefix, b.ID)
	}

	parsedFromPrefixed, err := ParseID(formatted)
	if err != nil {
		t.Fatalf("ParseID(%s): %v", formatted, err)
	}
	if parsedFromPrefixed != b.ID {
		t.Errorf("ParseID(%s) = %s, want %s", formatted, parsedFromPrefixed, b.ID)
	}

	parsedBare, err := ParseID(b.ID)
	if err != nil {
		t.Fatalf("ParseID(%s): %v", b.ID, err)
	}
	if parsedBare != b.ID {
		t.Errorf("ParseID(%s) = %s, want %s", b.ID, parsedBare, b.ID)
	}
}

// TestParseID_Rejects covers malformed IDs: wrong length, non-hex, and
// upper/mixed-case hex (canonical storage is lower-case; ParseID must not
// silently normalize case, since that would let two different-looking
// strings address the same Bead undetected upstream of this helper).
func TestParseID_Rejects(t *testing.T) {
	b, err := WithID(fixedBead())
	if err != nil {
		t.Fatalf("WithID: %v", err)
	}

	cases := []struct {
		name string
		id   string
	}{
		{"empty", ""},
		{"too short", b.ID[:10]},
		{"too long", b.ID + "00"},
		{"non-hex characters", "zz" + b.ID[2:]},
		{"upper-case hex", strings.ToUpper(b.ID)},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := ParseID(tc.id); err == nil {
				t.Errorf("ParseID(%q) = nil error, want error", tc.id)
			}
		})
	}
}

// equalStrings is a small test helper (avoids importing slices/reflect for
// a single comparison).
func equalStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
